name: 'CI'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run (jvm) unit tests
        run: ./gradlew jvmTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          check_name: JVM Unit Test Report
          report_paths: 'logger/build/test-results/jvmTest/TEST-*.xml'
