name: Central build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and run tests

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run jvmTest
        run: ./gradlew jvmTest
        if: matrix.os == 'ubuntu-latest'

      - name: Publish jvmTest report
        uses: mikepenz/action-junit-report@v4
        if: matrix.os == 'ubuntu-latest' && (success() || failure())
        with:
          check_name: jvmTest report
          report_paths: 'logger/build/test-results/jvmTest/TEST-*.xml'

      - name: Run iosX64Test
        run: ./gradlew iosX64Test
        if: matrix.os == 'macos-latest'

      - name: Publish iosX64Test report
        uses: mikepenz/action-junit-report@v4
        if: matrix.os == 'macos-latest' && (success() || failure())
        with:
          check_name: iosX64Test report
          report_paths: 'logger/build/test-results/iosX64Test/TEST-*.xml'
